### ISSUE TITLE
Fc8080 datasheet

### ISSUE THREAD

**Issue by vdbpeter** [AlbrechtL/AP8224-DAB-Dongle#4]
Hi, I'm hoping you have a full copy of the fc8080 datasheet,  as the link is no longer viable. The manufacturer doesnt seem to want to publish it any longer.  The other "online manuals" websites only reveal the first 10 pages.
Thanks

**Comment by AlbrechtL** [comment]
I put all datasheets in here https://github.com/AlbrechtL/AP8224-DAB-Dongle/tree/master/Datasheets

**Comment by vdbpeter** [comment]
Thanks- pity it's not the full document. Like what I found elsewhere,  it's the 'teaser' 1st 10 pages.
